export const getterTypes = {
  USERS: "USERS",
  IS_USERS_LOADING: "IS_USERS_LOADING"
};
export const mutationTypes = {
  ADD_USER_MUTATION: "ADD_USER_MUTATION",
  DELETE_USER_MUTATION: "DELETE_USER_MUTATION",
  UPDATE_STATUS_MUTATION: "UPDATE_STATUS_MUTATION",
  SET_USERS: "SET_USERS"
};
export const actionTypes = {
  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_STATUS: "UPDATE_STATUS",
  GET_USERS: "GET_USERS"
};
