export const getterTypes = {
  USERS: "USERS",
  IS_USERS_LOADING: "IS_USERS_LOADING",
  SELECTED_USER: "SELECTED_USER",
  IS_DETAIL_LOADING: "IS_DETAIL_LOADING"
};
export const mutationTypes = {
  ADD_USER_MUTATION: "ADD_USER_MUTATION",
  DELETE_USER_MUTATION: "DELETE_USER_MUTATION",
  UPDATE_STATUS_MUTATION: "UPDATE_STATUS_MUTATION",
  SET_USERS: "SET_USERS",
  SET_USER_BY_ID: "SET_USER_BY_ID",
  UPDATE_DETAIL_MUTATION: "UPDATE_DETAIL_MUTATION",
  SET_IS_DETAIL_LOADING: "SET_IS_DETAIL_LOADING"
};
export const actionTypes = {
  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_STATUS: "UPDATE_STATUS",
  GET_USERS: "GET_USERS",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  UPDATE_DETAIL: "UPDATE_DETAIL"
};
